
spring:
  config:
    import:
      - optional:classpath:application-server.yaml
      - optional:classpath:application-server-impl.yaml
      - optional:classpath:application-test.yaml
server:
  port: 8080